version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: vin_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: vin_db
      MYSQL_USER: vin_user
      MYSQL_PASSWORD: vin_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - vin_network

volumes:
  mysql_data:

networks:
  vin_network:
    driver: bridge
