"""initial migration

Revision ID: cf09392f6686
Revises: 
Create Date: 2025-06-11 14:26:01.687927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf09392f6686'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dealers',
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('dealer_id')
    )
    op.create_table('vehicles',
    sa.Column('model_id', sa.SmallInteger(), nullable=False),
    sa.Column('make', sa.String(length=255), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('model_id'),
    sa.UniqueConstraint('make', 'model', name='make_model')
    )
    op.create_table('dealer_websites',
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.dealer_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dealer_id')
    )
    op.create_table('listings',
    sa.Column('vin', sa.String(length=17), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('model_id', sa.SmallInteger(), nullable=False),
    sa.Column('trim', sa.String(length=255), nullable=True),
    sa.Column('dealer_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('certified', sa.Boolean(), nullable=False),
    sa.Column('style', sa.String(length=255), nullable=True),
    sa.Column('driven_wheels', sa.String(length=255), nullable=True),
    sa.Column('engine', sa.String(length=255), nullable=True),
    sa.Column('fuel_type', sa.String(length=255), nullable=True),
    sa.Column('exterior_color', sa.String(length=255), nullable=True),
    sa.Column('interior_color', sa.String(length=255), nullable=True),
    sa.Column('first_seen', sa.Date(), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=False),
    sa.Column('vdp_last_seen', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['dealer_id'], ['dealers.dealer_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['vehicles.model_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vin')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index('idx_mileage', ['mileage'], unique=False)
        batch_op.create_index('idx_year_model', ['year', 'model_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index('idx_year_model')
        batch_op.drop_index('idx_mileage')

    op.drop_table('listings')
    op.drop_table('dealer_websites')
    op.drop_table('vehicles')
    op.drop_table('dealers')
    # ### end Alembic commands ###
